### ISSUE TITLE
[BUG] Twinkle tray crashes my computer. The excpetion breakpoint. A breakpoint has been reached.

### ISSUE THREAD

**Issue by bigplayer-ai** [xanderfrangos/twinkle-tray#553]
Hey,
Twinkle tray crashes my computer.
![2023-02-26_21-50-21](https://user-images.githubusercontent.com/119108387/221881042-3a3d705c-2b81-4905-92f6-7939e45b28d5.jpg)
I am using windows 11 22h2 build 22621.1265 with the lastest version of twinkle tray
I just uninstalled twinkle tray untill the issue is resolved.

**Comment by bigplayer-ai** [comment]
Yes exactly this happens to me too.

**Comment by fancymans** [comment]
same issue here on windows 11 during restart. not sure what’s the source of the issue since it occurs almost randomly. i haven’t noticed a pattern of what triggers it.

**Comment by FurkanKambay** [comment]
Have gotten this several times. Have you looked into this @xanderfrangos ? I feel like it's happening cause you released the debug build maybe?

**Comment by okzea** [comment]
I'm also having this error

**Comment by adrianghc** [comment]
Same issue here.

**Comment by amanzer** [comment]
The issue still occurs alot.

**Comment by patin-osu** [comment]
Yeah i still get this error on every shutdown and restart, i hope it'll get fix soon
![IMG_20240101_151305_329](https://github.com/xanderfrangos/twinkle-tray/assets/75104667/64d23ef5-4500-4301-acad-f82db0710d62)

**Comment by xanderfrangos** [comment]
v1.16.0 should resolve this, once released. I haven't seen it happen in the beta version for quite a while.

**Comment by HarinderG** [comment]
![IMG_0981](https://github.com/xanderfrangos/twinkle-tray/assets/15056631/f2cc3679-92a8-4ee3-816d-8a8f651f56a2)
Been getting the same issue on two different machines on shutdown or restart.

**Comment by paramvir-phagura** [comment]
> ![IMG_0981](https://private-user-images.githubusercontent.com/15056631/324622566-f2cc3679-92a8-4ee3-816d-8a8f651f56a2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTI1NjcsIm5iZiI6MTczMjgxMjI2NywicGF0aCI6Ii8xNTA1NjYzMS8zMjQ2MjI1NjYtZjJjYzM2NzktOTJhOC00ZWUzLTgxNmQtOGE4ZjY1MWY1NmEyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjQ0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDhjMDY3ZGIyY2QxOTU0Yzg3NTNiZmI1MjQxYmVhZGY4YzA2NTFkNmIwOTAxYWRlNThlNWYzNzM4MDNmYzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BLsNfcwn0MowEqqOQ6Tifuy9TLFrXI_MsCUJ_DoYpmY) Been getting the same issue on two different machines on shutdown or restart.

I'm still having the same issue on every shutdown/restart. Any resolution to this?
